import React, { useState } from "react";

import { api } from "@/lib/api";
import { toast } from "@/hooks/use-toast";

export default function DiscountCreateForm() {
 
  const [form, setForm] = useState({
    membership: "",
    discountType: "percentage",
    amount: 0,
    expiresAt: "",
    isOneTime: true,
  });

  const [loading, setLoading] = useState(false);
  const [generatedCode, setGeneratedCode] = useState("");

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);

    try {
      const token = localStorage.getItem("token");
      if (!token) {
        toast({
          title: "Unauthorized",
          description: "You must be logged in to create a discount.",
          variant: "destructive",
        });
        setLoading(false);
        return;
      }

      const payload = { ...form, token };
      const response = await api.submitCustomerDetails(payload, "create");

      if (response.success) {
        const code = response.data.code || "N/A";
        setGeneratedCode(code);

        toast({
          title: "Discount Created",
          description: `Discount created successfully: ${code}`,
        });

        setForm({
          membership: "",
          discountType: "percentage",
          amount: 0,
          expiresAt: "",
          isOneTime: true,
        });
      } else {
        toast({
          title: "Creation Failed",
          description: response.error || response.message || "Unable to create discount",
          variant: "destructive",
        });
      }
    } catch (err: any) {
      toast({
        title: "Server Error",
        description: "Could not connect to the server. Please try again later.",
        variant: "destructive",
      });
    } finally {
      setLoading(false);
    }
  };

const handleLogout = () => {
  localStorage.clear();
  window.location.href = "/login";
};

  const copyToClipboard = () => {
    if (!generatedCode) return;
    navigator.clipboard.writeText(generatedCode);
    toast({ title: "Copied!", description: "Discount code copied to clipboard." });
  };

  return (
    <div className="min-h-screen flex flex-col items-center justify-start bg-gray-50 p-4">
      {/* Top bar with Logout */}
      <div className="w-full max-w-md flex justify-end mb-4">
        <button
          onClick={handleLogout}
          className="px-4 py-2 bg-red-500 text-white rounded-lg hover:bg-red-600"
        >
          Logout
        </button>
      </div>

      <div className="w-full max-w-md bg-white shadow-md rounded-xl p-6 border border-gray-200">
        <h2 className="text-2xl font-bold mb-6 text-center text-primary">
          Create Discount Code
        </h2>

        <form onSubmit={handleSubmit} className="space-y-5">
          {/* Code (read-only) with copy button */}
          <div className="relative">
            <label className="block font-medium mb-1">Discount Code</label>
            <input
              type="text"
              value={generatedCode || "Will be generated by server"}
              readOnly
              className="w-full border rounded-lg p-2 pr-24 bg-gray-100 text-gray-600"
            />
            {generatedCode && (
              <button
                type="button"
                onClick={copyToClipboard}
                className="absolute top-12 right-2 -translate-y-1/2 px-3 py-1 bg-primary text-white rounded-lg hover:bg-primary/90"
              >
                Copy
              </button>
            )}
          </div>

          {/* Membership Type */}
          <div>
            <label className="block font-medium mb-1">Membership Group</label>
            <select
              value={form.membership || ""}
              onChange={(e) => setForm({ ...form, membership: e.target.value })}
              className="w-full border rounded-lg p-2 focus:ring focus:ring-primary/30"
              required
            >
              <option value="">Select Group</option>
              <option value="BBG">BBG (British Business Group)</option>
              <option value="NBCC">NBCC (Nigeria British Chamber of Commerce)</option>
            </select>
          </div>


          {/* Discount Type */}
          <div>
            <label className="block font-medium mb-1">Discount Type</label>
            <select
              value={form.discountType}
              onChange={(e) => setForm({ ...form, discountType: e.target.value })}
              className="w-full border rounded-lg p-2 focus:ring focus:ring-primary/30"
            >
              <option value="percentage">Percentage (%)</option>
              <option value="fixed">Fixed Amount</option>
            </select>
          </div>

          {/* Amount */}
          <div>
            <label className="block font-medium mb-1">
              Amount {form.discountType === "percentage" && "(%)"}
            </label>
            <input
              type="number"
              value={form.amount}
              onChange={(e) => setForm({ ...form, amount: Number(e.target.value) })}
              className="w-full border rounded-lg p-2 focus:ring focus:ring-primary/30"
            />
          </div>

          {/* Expiry */}
          <div>
            <label className="block font-medium mb-1">Expiry Date</label>
            <input
              type="date"
              value={form.expiresAt}
              onChange={(e) => setForm({ ...form, expiresAt: e.target.value })}
              className="w-full border rounded-lg p-2 focus:ring focus:ring-primary/30"
            />
          </div>

          {/* One-time use */}
          <div className="flex items-center gap-3">
            <input
              type="checkbox"
              checked={form.isOneTime}
              onChange={(e) => setForm({ ...form, isOneTime: e.target.checked })}
              className="w-5 h-5 accent-primary"
            />
            <span className="font-medium">One-time use only</span>
          </div>

          {/* Submit */}
          <button
            type="submit"
            disabled={loading}
            className="w-full py-3 bg-primary text-white rounded-lg text-lg font-medium hover:bg-primary/90 disabled:opacity-50"
          >
            {loading ? "Creating..." : "Create Discount"}
          </button>
        </form>
      </div>
    </div>
  );
}
